
name: Run Apartments Reservation Producer

on:
  workflow_dispatch:  # Allows manual trigger
 # Trigger this action on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install SSH client
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # Step 3: SSH into the VPS and pull the latest code
      - name: Deploy Docker Compose on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 158.220.124.0
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ./new-kafka  # Navigate to the directory where you want to deploy
            git pull origin master     # Pull the latest changes
            source venv/bin/activate
            cd 'Apartment Resident Issues'
            python3 apartment.py
